import type { CareerPath, RunnerAct } from '../../../types';

export type UpgradeCategory =
  | 'act1_universal'
  | 'act2_hustle'
  | 'act2_path'
  | 'act3_base'
  | 'act3_branch_a'
  | 'act3_branch_b'
  | 'act4_path'
  | 'ghost_universal'
  | 'ghost_path';

export type CostResource = 'eddies' | 'secondary' | 'influence' | 'contacts' | 'rep' | 'ghost_tokens';

export interface UpgradeDef {
  id: string;
  name: string;
  flavour: string;
  stat: string;
  category: UpgradeCategory;
  act: RunnerAct;
  path?: CareerPath;
  branch?: 'a' | 'b';
  cost: number;
  costResource: CostResource;
  secondaryCost?: number;
  // Income modifiers
  incomeMod?: number;         // flat eddie/s addition
  incomeMultMod?: number;     // multiplier stacked on income
  secondaryGenMod?: number;   // secondary resource/s addition
  secondaryIncomeMod?: number;// flat eddie/s per secondary resource held
  influenceGenMod?: number;   // influence/s addition
  offlineCapHours?: number;   // ghost memory offline cap
  prereq?: string[];          // upgrade IDs required before this
  maxLevel?: number;          // default 1 (one-time)
}

// ─── ACT 1 UNIVERSAL ───────────────────────────────────────────────────────

export const ACT1_UPGRADES: UpgradeDef[] = [
  {
    id: 'a1_burner_rig',
    name: 'Burner Rig',
    flavour: 'Scraped together from three dead datapads and a prayer.',
    stat: '+0.5 eddies/sec',
    category: 'act1_universal',
    act: 1,
    cost: 50,
    costResource: 'eddies',
    incomeMod: 0.5,
  },
  {
    id: 'a1_street_contacts',
    name: 'Street Contacts',
    flavour: 'Everyone owes someone. Time to start collecting.',
    stat: '+0.2 contacts/sec',
    category: 'act1_universal',
    act: 1,
    cost: 200,
    costResource: 'eddies',
    secondaryGenMod: 0.2,
    prereq: ['a1_burner_rig'],
  },
  {
    id: 'a1_shadow_wallet',
    name: 'Shadow Wallet',
    flavour: 'Untraceable. Mostly.',
    stat: '+2 eddies/sec',
    category: 'act1_universal',
    act: 1,
    cost: 750,
    costResource: 'eddies',
    incomeMod: 2,
    prereq: ['a1_street_contacts'],
  },
  {
    id: 'a1_back_alley_hustle',
    name: 'Back Alley Hustle',
    flavour: 'Know the right corners. Know the right hours.',
    stat: '+5 eddies/sec, +0.5 contacts/sec',
    category: 'act1_universal',
    act: 1,
    cost: 2500,
    costResource: 'eddies',
    incomeMod: 5,
    secondaryGenMod: 0.5,
    prereq: ['a1_shadow_wallet'],
  },
  {
    id: 'a1_black_market_feed',
    name: 'Black Market Feed',
    flavour: 'The corps flood the market. The streets drain it.',
    stat: '×1.2 income multiplier',
    category: 'act1_universal',
    act: 1,
    cost: 8000,
    costResource: 'eddies',
    incomeMultMod: 1.2,
    prereq: ['a1_back_alley_hustle'],
  },
  {
    id: 'a1_darknet_relay',
    name: 'Darknet Relay',
    flavour: 'The NET never sleeps. Neither does your income.',
    stat: 'Offline cap +2 hrs',
    category: 'act1_universal',
    act: 1,
    cost: 15000,
    costResource: 'eddies',
    offlineCapHours: 2,
    prereq: ['a1_black_market_feed'],
  },
  {
    id: 'a1_ghost_address',
    name: 'Ghost Address',
    flavour: 'They can look. They won\'t find anything.',
    stat: 'Random event penalties -25%',
    category: 'act1_universal',
    act: 1,
    cost: 25000,
    costResource: 'eddies',
    prereq: ['a1_darknet_relay'],
  },
];

// ─── ACT 2 HUSTLE (universal income upgrades available to all paths) ────────

export const ACT2_HUSTLE_UPGRADES: UpgradeDef[] = [
  {
    id: 'h2_encrypted_accounts',
    name: 'Encrypted Accounts',
    flavour: 'Money with no paper trail.',
    stat: '+15 eddies/sec',
    category: 'act2_hustle',
    act: 2,
    cost: 50000,
    costResource: 'eddies',
    incomeMod: 15,
  },
  {
    id: 'h2_shell_companies',
    name: 'Shell Companies',
    flavour: 'Three layers of corporate abstraction. Clean as a corpo handshake.',
    stat: '×1.3 income',
    category: 'act2_hustle',
    act: 2,
    cost: 150000,
    costResource: 'eddies',
    incomeMultMod: 1.3,
    prereq: ['h2_encrypted_accounts'],
  },
  {
    id: 'h2_market_access',
    name: 'Grey Market Access',
    flavour: 'Not illegal. Adjacent to illegal.',
    stat: '+50 eddies/sec',
    category: 'act2_hustle',
    act: 2,
    cost: 500000,
    costResource: 'eddies',
    incomeMod: 50,
    prereq: ['h2_shell_companies'],
  },
  {
    id: 'h2_rep_network',
    name: 'Rep Network',
    flavour: 'Your name does half the work.',
    stat: '×1.5 income',
    category: 'act2_hustle',
    act: 2,
    cost: 2000000,
    costResource: 'eddies',
    incomeMultMod: 1.5,
    prereq: ['h2_market_access'],
  },
];

// ─── SOLO PATH ──────────────────────────────────────────────────────────────

export const SOLO_UPGRADES: UpgradeDef[] = [
  {
    id: 'solo_first_contract',
    name: 'First Contract',
    flavour: 'Ugly work. Pays well. You\'re suited for it.',
    stat: 'Unlocks Heat generation (+0.5 Heat/sec)',
    category: 'act2_path',
    act: 2,
    path: 'solo',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
  },
  {
    id: 'solo_combat_suite',
    name: 'Combat Suite',
    flavour: 'The right chrome in the right places.',
    stat: '+10 eddies/sec per Heat',
    category: 'act2_path',
    act: 2,
    path: 'solo',
    cost: 100000,
    costResource: 'eddies',
    secondaryIncomeMod: 10,
    prereq: ['solo_first_contract'],
  },
  {
    id: 'solo_target_package',
    name: 'Target Package',
    flavour: 'Corp dossiers. Home addresses. Everything you need.',
    stat: 'Eddie burst on Heat spend',
    category: 'act2_path',
    act: 2,
    path: 'solo',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['solo_combat_suite'],
  },
  {
    id: 'solo_trauma_team',
    name: 'Trauma Team Contact',
    flavour: 'Not cheap. Worth every eurodollar.',
    stat: 'Heat blowback events -40%',
    category: 'act2_path',
    act: 2,
    path: 'solo',
    cost: 500000,
    costResource: 'eddies',
    prereq: ['solo_first_contract'],
  },
  {
    id: 'solo_corp_dossier',
    name: 'Corp Dossier',
    flavour: 'Know the target. Know the exits.',
    stat: 'Max Heat cap +50',
    category: 'act2_path',
    act: 2,
    path: 'solo',
    cost: 1000000,
    costResource: 'eddies',
    prereq: ['solo_trauma_team'],
  },
  {
    id: 'solo_black_ops_clearance',
    name: 'Black Ops Clearance',
    flavour: 'The jobs nobody talks about. The pay nobody refuses.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'solo',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['solo_corp_dossier'],
  },
  // Act 3 Branch A — Corporate Cleaner
  {
    id: 'solo_militech_contract',
    name: 'Militech Contract',
    flavour: 'You don\'t ask what\'s in the package.',
    stat: '+500 eddies/sec',
    category: 'act3_branch_a',
    act: 3,
    path: 'solo',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 500,
  },
  {
    id: 'solo_deniable_asset',
    name: 'Deniable Asset Status',
    flavour: 'You were never there. This never happened.',
    stat: 'Income immune during corp events',
    category: 'act3_branch_a',
    act: 3,
    path: 'solo',
    branch: 'a',
    cost: 15000000,
    costResource: 'eddies',
    prereq: ['solo_militech_contract'],
  },
  {
    id: 'solo_extraction_spec',
    name: 'Executive Extraction Specialist',
    flavour: 'Alive or not is up to the client.',
    stat: 'Massive eddie burst upgrades',
    category: 'act3_branch_a',
    act: 3,
    path: 'solo',
    branch: 'a',
    cost: 50000000,
    costResource: 'eddies',
    prereq: ['solo_deniable_asset'],
  },
  {
    id: 'solo_ghost_contractor',
    name: 'Ghost Contractor',
    flavour: 'No name. No face. Just results.',
    stat: 'Permanent Heat reduction per job',
    category: 'act3_branch_a',
    act: 3,
    path: 'solo',
    branch: 'a',
    cost: 150000000,
    costResource: 'eddies',
    prereq: ['solo_extraction_spec'],
  },
  // Act 3 Branch B — Vigilante
  {
    id: 'solo_street_protection',
    name: 'Street Protection Network',
    flavour: 'The corps don\'t protect anyone. You do.',
    stat: 'Rep-scaled passive income',
    category: 'act3_branch_b',
    act: 3,
    path: 'solo',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
  },
  {
    id: 'solo_safe_houses',
    name: 'Community Safe Houses',
    flavour: 'Doors that open for the right people.',
    stat: 'All event damage -30%',
    category: 'act3_branch_b',
    act: 3,
    path: 'solo',
    branch: 'b',
    cost: 15000000,
    costResource: 'eddies',
    prereq: ['solo_street_protection'],
  },
  {
    id: 'solo_neighbourhood_watch',
    name: 'Neighbourhood Watch',
    flavour: 'Everyone looks out for everyone.',
    stat: 'Contacts generate secondary income',
    category: 'act3_branch_b',
    act: 3,
    path: 'solo',
    branch: 'b',
    cost: 50000000,
    costResource: 'eddies',
    prereq: ['solo_safe_houses'],
  },
  {
    id: 'solo_living_legend',
    name: 'Living Legend',
    flavour: 'They don\'t come after legends. Legends come after them.',
    stat: 'Rep multiplier caps increase',
    category: 'act3_branch_b',
    act: 3,
    path: 'solo',
    branch: 'b',
    cost: 150000000,
    costResource: 'eddies',
    prereq: ['solo_neighbourhood_watch'],
  },
];

// ─── NETRUNNER PATH ──────────────────────────────────────────────────────────

export const NETRUNNER_UPGRADES: UpgradeDef[] = [
  {
    id: 'nr_ghost_node',
    name: 'Ghost Node',
    flavour: 'Running dark in the deep NET.',
    stat: 'Unlocks Bandwidth generation (+0.5 Bandwidth/sec)',
    category: 'act2_path',
    act: 2,
    path: 'netrunner',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
  },
  {
    id: 'nr_data_broker',
    name: 'Data Broker Access',
    flavour: 'Someone buys everything. You know where to sell.',
    stat: '+8 eddies/sec per Bandwidth',
    category: 'act2_path',
    act: 2,
    path: 'netrunner',
    cost: 100000,
    costResource: 'eddies',
    secondaryIncomeMod: 8,
    prereq: ['nr_ghost_node'],
  },
  {
    id: 'nr_ice_farm',
    name: 'ICE Farm',
    flavour: 'Black ICE is expensive. Growing your own is cheaper.',
    stat: 'Bandwidth cap +100',
    category: 'act2_path',
    act: 2,
    path: 'netrunner',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['nr_data_broker'],
  },
  {
    id: 'nr_stealth_routing',
    name: 'Stealth Routing',
    flavour: 'The signal that wasn\'t there.',
    stat: 'Detection events -40%',
    category: 'act2_path',
    act: 2,
    path: 'netrunner',
    cost: 500000,
    costResource: 'eddies',
    prereq: ['nr_ghost_node'],
  },
  {
    id: 'nr_subnet_expansion',
    name: 'Subnet Expansion',
    flavour: 'More nodes. More income. More risk.',
    stat: '+1 Bandwidth/sec',
    category: 'act2_path',
    act: 2,
    path: 'netrunner',
    cost: 1000000,
    costResource: 'eddies',
    secondaryGenMod: 1,
    prereq: ['nr_stealth_routing'],
  },
  {
    id: 'nr_deep_access_protocol',
    name: 'Deep Access Protocol',
    flavour: 'Somewhere Netwatch can\'t reach. Almost.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'netrunner',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['nr_subnet_expansion'],
  },
  // Act 3 Branch A — Ghost Archive
  {
    id: 'nr_dead_drop_network',
    name: 'Dead Drop Network',
    flavour: 'Data stored where no one looks.',
    stat: 'Massive offline earnings',
    category: 'act3_branch_a',
    act: 3,
    path: 'netrunner',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    offlineCapHours: 8,
  },
  {
    id: 'nr_encrypted_vault',
    name: 'Encrypted Vault',
    flavour: 'Even you need a key to open this.',
    stat: 'Eddie storage ×2',
    category: 'act3_branch_a',
    act: 3,
    path: 'netrunner',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['nr_dead_drop_network'],
  },
  {
    id: 'nr_cold_data_market',
    name: 'Cold Data Market',
    flavour: 'Old data is still data. Someone always wants it.',
    stat: 'Passively sells archived data',
    category: 'act3_branch_a',
    act: 3,
    path: 'netrunner',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['nr_encrypted_vault'],
    incomeMod: 1000,
  },
  {
    id: 'nr_phantom_subnet',
    name: 'Phantom Subnet',
    flavour: 'It exists everywhere and nowhere.',
    stat: 'Undetectable passive income',
    category: 'act3_branch_a',
    act: 3,
    path: 'netrunner',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['nr_cold_data_market'],
    incomeMultMod: 2,
  },
  // Act 3 Branch B — Black Market Broker
  {
    id: 'nr_realtime_data',
    name: 'Real-Time Data Sales',
    flavour: 'Fresh data. Premium rates.',
    stat: 'Income spike events',
    category: 'act3_branch_b',
    act: 3,
    path: 'netrunner',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
  },
  {
    id: 'nr_corp_intel_feed',
    name: 'Corporate Intel Feed',
    flavour: 'They pay well for what they already know.',
    stat: 'Eddie burst on Bandwidth spend',
    category: 'act3_branch_b',
    act: 3,
    path: 'netrunner',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['nr_realtime_data'],
  },
  {
    id: 'nr_shadow_exchange',
    name: 'Shadow Exchange',
    flavour: 'The market the corps pretend doesn\'t exist.',
    stat: 'Live data market access',
    category: 'act3_branch_b',
    act: 3,
    path: 'netrunner',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['nr_corp_intel_feed'],
    incomeMod: 800,
  },
  {
    id: 'nr_honeypot',
    name: 'Netwatch Honeypot',
    flavour: 'Let them come. Charge them for the experience.',
    stat: 'Detection events become income events',
    category: 'act3_branch_b',
    act: 3,
    path: 'netrunner',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['nr_shadow_exchange'],
    incomeMultMod: 1.8,
  },
];

// ─── FIXER PATH ──────────────────────────────────────────────────────────────

export const FIXER_UPGRADES: UpgradeDef[] = [
  {
    id: 'fx_street_network',
    name: 'Street Network',
    flavour: 'Everyone needs someone. You are that someone.',
    stat: 'Unlocks Connections generation (+0.5/sec)',
    category: 'act2_path',
    act: 2,
    path: 'fixer',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
  },
  {
    id: 'fx_contract_broker',
    name: 'Contract Broker',
    flavour: 'A percentage of everything. The math adds up.',
    stat: '+6 eddies/sec per Connection',
    category: 'act2_path',
    act: 2,
    path: 'fixer',
    cost: 100000,
    costResource: 'eddies',
    secondaryIncomeMod: 6,
    prereq: ['fx_street_network'],
  },
  {
    id: 'fx_retainer_list',
    name: 'Retainer List',
    flavour: 'Reliable talent. Expensive taste.',
    stat: 'Connections cap +100',
    category: 'act2_path',
    act: 2,
    path: 'fixer',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['fx_contract_broker'],
  },
  {
    id: 'fx_rep_shield',
    name: 'Reputation Shield',
    flavour: 'Your rep is the armour. Polish it.',
    stat: 'Rival fixer events -40%',
    category: 'act2_path',
    act: 2,
    path: 'fixer',
    cost: 500000,
    costResource: 'eddies',
    prereq: ['fx_street_network'],
  },
  {
    id: 'fx_preferred_vendor',
    name: 'Preferred Vendor Status',
    flavour: 'First call. Last resort. All the margins.',
    stat: '+1 Connection/sec',
    category: 'act2_path',
    act: 2,
    path: 'fixer',
    cost: 1000000,
    costResource: 'eddies',
    secondaryGenMod: 1,
    prereq: ['fx_rep_shield'],
  },
  {
    id: 'fx_senior_fixer_status',
    name: 'Senior Fixer Status',
    flavour: 'The name alone opens doors.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'fixer',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['fx_preferred_vendor'],
  },
  // Act 3 Branch A — Crime Syndicate
  {
    id: 'fx_volume_contracts',
    name: 'Volume Contracts',
    flavour: 'Small margins. Large volume. Same result.',
    stat: 'High-frequency small contract income',
    category: 'act3_branch_a',
    act: 3,
    path: 'fixer',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 400,
  },
  {
    id: 'fx_territory_control',
    name: 'Territory Control',
    flavour: 'The blocks that pay you to exist.',
    stat: 'Area-based passive income',
    category: 'act3_branch_a',
    act: 3,
    path: 'fixer',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['fx_volume_contracts'],
    incomeMod: 800,
  },
  {
    id: 'fx_enforcement_arm',
    name: 'Enforcement Arm',
    flavour: 'Insurance. Heavy insurance.',
    stat: 'All hostile events -35%',
    category: 'act3_branch_a',
    act: 3,
    path: 'fixer',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['fx_territory_control'],
  },
  {
    id: 'fx_distribution_network',
    name: 'Distribution Network',
    flavour: 'Moving everything. Touching nothing.',
    stat: 'All resource generation +',
    category: 'act3_branch_a',
    act: 3,
    path: 'fixer',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['fx_enforcement_arm'],
    incomeMultMod: 2,
  },
  // Act 3 Branch B — Elite Broker
  {
    id: 'fx_platinum_list',
    name: 'Platinum Client List',
    flavour: 'One client. Bigger than your last ten.',
    stat: 'Fewer but massive contracts',
    category: 'act3_branch_b',
    act: 3,
    path: 'fixer',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 600,
  },
  {
    id: 'fx_corp_liaison',
    name: 'Corporate Liaison',
    flavour: 'They need what you provide. They hate that they need it.',
    stat: 'Tier-1 corpo contract access',
    category: 'act3_branch_b',
    act: 3,
    path: 'fixer',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['fx_platinum_list'],
    incomeMod: 1500,
  },
  {
    id: 'fx_exclusivity_clause',
    name: 'Exclusivity Clause',
    flavour: 'You work for them. And only them. For now.',
    stat: 'Income immunity periods',
    category: 'act3_branch_b',
    act: 3,
    path: 'fixer',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['fx_corp_liaison'],
  },
  {
    id: 'fx_black_book',
    name: 'The Black Book',
    flavour: 'Every name in it is worth a fortune. The book itself is priceless.',
    stat: 'Legendary contact roster — ×2 income',
    category: 'act3_branch_b',
    act: 3,
    path: 'fixer',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['fx_exclusivity_clause'],
    incomeMultMod: 2,
  },
];

// ─── TECH PATH ──────────────────────────────────────────────────────────────

export const TECH_UPGRADES: UpgradeDef[] = [
  {
    id: 'tech_salvage_op',
    name: 'Salvage Operation',
    flavour: 'One corp\'s junk. Your income.',
    stat: 'Unlocks Parts generation (+0.5 Parts/sec)',
    category: 'act2_path',
    act: 2,
    path: 'tech',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
  },
  {
    id: 'tech_production_queue',
    name: 'Production Queue',
    flavour: 'Parts in. Product out. Eddies in.',
    stat: '+5 eddies/sec per Part',
    category: 'act2_path',
    act: 2,
    path: 'tech',
    cost: 100000,
    costResource: 'eddies',
    secondaryIncomeMod: 5,
    prereq: ['tech_salvage_op'],
  },
  {
    id: 'tech_workshop_expansion',
    name: 'Workshop Expansion',
    flavour: 'More floor space. More production.',
    stat: 'Parts cap +200',
    category: 'act2_path',
    act: 2,
    path: 'tech',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['tech_production_queue'],
  },
  {
    id: 'tech_supply_chain',
    name: 'Supply Chain',
    flavour: 'The parts flow or the work stops. Keep them flowing.',
    stat: '+1 Parts/sec',
    category: 'act2_path',
    act: 2,
    path: 'tech',
    cost: 500000,
    costResource: 'eddies',
    secondaryGenMod: 1,
    prereq: ['tech_salvage_op'],
  },
  {
    id: 'tech_reverse_engineering',
    name: 'Reverse Engineering',
    flavour: 'They spent millions building it. You spend hours taking it apart.',
    stat: 'Converts corp tech to Parts',
    category: 'act2_path',
    act: 2,
    path: 'tech',
    cost: 1000000,
    costResource: 'eddies',
    prereq: ['tech_supply_chain'],
  },
  {
    id: 'tech_black_market_distribution',
    name: 'Black Market Distribution',
    flavour: 'Legal channels take a cut. These don\'t.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'tech',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['tech_reverse_engineering'],
  },
  // Act 3 Branch A — Weapons Manufacture
  {
    id: 'tech_weapons_grade',
    name: 'Weapons Grade Materials',
    flavour: 'The good stuff. Costs more. Worth more.',
    stat: 'High Parts cost, massive return',
    category: 'act3_branch_a',
    act: 3,
    path: 'tech',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 500,
  },
  {
    id: 'tech_militech_grey',
    name: 'Militech Grey Contract',
    flavour: 'Deniable. Lucrative. Irregular.',
    stat: 'Irregular massive income bursts',
    category: 'act3_branch_a',
    act: 3,
    path: 'tech',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['tech_weapons_grade'],
  },
  {
    id: 'tech_custom_fab',
    name: 'Custom Fab Line',
    flavour: 'One of a kind. For the right price.',
    stat: 'Unique high-value items',
    category: 'act3_branch_a',
    act: 3,
    path: 'tech',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['tech_militech_grey'],
    incomeMod: 2000,
  },
  {
    id: 'tech_armour_division',
    name: 'Armour Division',
    flavour: 'They always need more. You always have more.',
    stat: 'Income during conflict events',
    category: 'act3_branch_a',
    act: 3,
    path: 'tech',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['tech_custom_fab'],
    incomeMultMod: 2,
  },
  // Act 3 Branch B — Cyberware Lab
  {
    id: 'tech_cyberware_suite',
    name: 'Cyberware Suite',
    flavour: 'Premium chrome. Premium margins.',
    stat: 'Produces premium implants',
    category: 'act3_branch_b',
    act: 3,
    path: 'tech',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 600,
  },
  {
    id: 'tech_raven_access',
    name: 'Raven Microcybernetics Access',
    flavour: 'They left the door open. Technically.',
    stat: 'Advanced component supply',
    category: 'act3_branch_b',
    act: 3,
    path: 'tech',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['tech_cyberware_suite'],
  },
  {
    id: 'tech_chrome_clinic',
    name: 'Chrome Clinic Partnership',
    flavour: 'They install it. You built it.',
    stat: 'Recurring medtech income',
    category: 'act3_branch_b',
    act: 3,
    path: 'tech',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['tech_raven_access'],
    incomeMod: 1500,
  },
  {
    id: 'tech_humanity_research',
    name: 'Humanity Research',
    flavour: 'The cost of chrome. The profit of understanding it.',
    stat: 'Rep converts to income multiplier',
    category: 'act3_branch_b',
    act: 3,
    path: 'tech',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['tech_chrome_clinic'],
    incomeMultMod: 1.8,
  },
];

// ─── MEDTECH PATH ────────────────────────────────────────────────────────────

export const MEDTECH_UPGRADES: UpgradeDef[] = [
  {
    id: 'med_first_clinic',
    name: 'First Clinic',
    flavour: 'It\'s not much. It\'s enough.',
    stat: 'Unlocks Patients generation (+0.3/sec)',
    category: 'act2_path',
    act: 2,
    path: 'medtech',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.3,
  },
  {
    id: 'med_treatment_protocol',
    name: 'Treatment Protocol',
    flavour: 'Standardise the care. Stabilise the income.',
    stat: '+12 eddies/sec per Patient',
    category: 'act2_path',
    act: 2,
    path: 'medtech',
    cost: 100000,
    costResource: 'eddies',
    secondaryIncomeMod: 12,
    prereq: ['med_first_clinic'],
  },
  {
    id: 'med_clinic_expansion',
    name: 'Clinic Expansion',
    flavour: 'More beds. More cases. More eddies.',
    stat: 'Patients cap +50',
    category: 'act2_path',
    act: 2,
    path: 'medtech',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['med_treatment_protocol'],
  },
  {
    id: 'med_supply_contract',
    name: 'Supply Contract',
    flavour: 'Grey market pharma. Works just as well.',
    stat: '+0.5 Patients/sec',
    category: 'act2_path',
    act: 2,
    path: 'medtech',
    cost: 500000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
    prereq: ['med_first_clinic'],
  },
  {
    id: 'med_offgrid_pharmacy',
    name: 'Off-Grid Pharmacy',
    flavour: 'Supply events can\'t hit what they can\'t find.',
    stat: 'Supply event penalties -40%',
    category: 'act2_path',
    act: 2,
    path: 'medtech',
    cost: 1000000,
    costResource: 'eddies',
    prereq: ['med_supply_contract'],
  },
  {
    id: 'med_trauma_specialisation',
    name: 'Trauma Specialisation',
    flavour: 'The hard cases. The paying cases.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'medtech',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['med_offgrid_pharmacy'],
  },
  // Act 3 Branch A — Shadow Hospital
  {
    id: 'med_high_volume',
    name: 'High Volume Intake',
    flavour: 'Triage the triage.',
    stat: 'Maximum Patients capacity',
    category: 'act3_branch_a',
    act: 3,
    path: 'medtech',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 400,
  },
  {
    id: 'med_emergency_triage',
    name: 'Emergency Triage',
    flavour: 'When it goes wrong, you get busier.',
    stat: 'Income during crisis events',
    category: 'act3_branch_a',
    act: 3,
    path: 'medtech',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['med_high_volume'],
  },
  {
    id: 'med_community_trust',
    name: 'Community Trust',
    flavour: 'Trust is harder to build than a clinic.',
    stat: 'Patients generate rep multiplier',
    category: 'act3_branch_a',
    act: 3,
    path: 'medtech',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['med_emergency_triage'],
  },
  {
    id: 'med_underground_network',
    name: 'The Underground Network',
    flavour: 'City-wide. Invisible. Essential.',
    stat: 'City-wide patient referral system',
    category: 'act3_branch_a',
    act: 3,
    path: 'medtech',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['med_community_trust'],
    incomeMultMod: 2,
  },
  // Act 3 Branch B — Pharma Network
  {
    id: 'med_supply_compound',
    name: 'Supply Chain Compound',
    flavour: 'Interest on interest on interest.',
    stat: 'Compounding income over time',
    category: 'act3_branch_b',
    act: 3,
    path: 'medtech',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 500,
  },
  {
    id: 'med_synthetic_production',
    name: 'Synthetic Production',
    flavour: 'Not natural. Effective. Profitable.',
    stat: 'Removes supply dependency',
    category: 'act3_branch_b',
    act: 3,
    path: 'medtech',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['med_supply_compound'],
  },
  {
    id: 'med_distribution_net',
    name: 'Distribution Network',
    flavour: 'Gets where it needs to go. No questions.',
    stat: 'Recurring passive income',
    category: 'act3_branch_b',
    act: 3,
    path: 'medtech',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['med_synthetic_production'],
    incomeMod: 2000,
  },
  {
    id: 'med_premium_clients',
    name: 'Premium Client Access',
    flavour: 'The corps keep their people alive. You keep their people alive.',
    stat: 'Influence-gated high-value patients',
    category: 'act3_branch_b',
    act: 3,
    path: 'medtech',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['med_distribution_net'],
    incomeMultMod: 2.5,
  },
];

// ─── ROCKERBOY PATH ──────────────────────────────────────────────────────────

export const ROCKERBOY_UPGRADES: UpgradeDef[] = [
  {
    id: 'rb_first_broadcast',
    name: 'First Broadcast',
    flavour: 'They heard it. They can\'t unhear it.',
    stat: 'Unlocks Followers generation (+1/sec)',
    category: 'act2_path',
    act: 2,
    path: 'rockerboy',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 1,
  },
  {
    id: 'rb_cultural_resonance',
    name: 'Cultural Resonance',
    flavour: 'The signal in the noise.',
    stat: '+3 eddies/sec per Follower',
    category: 'act2_path',
    act: 2,
    path: 'rockerboy',
    cost: 100000,
    costResource: 'eddies',
    secondaryIncomeMod: 3,
    prereq: ['rb_first_broadcast'],
  },
  {
    id: 'rb_platform_expansion',
    name: 'Platform Expansion',
    flavour: 'More channels. More reach.',
    stat: 'Followers cap +500',
    category: 'act2_path',
    act: 2,
    path: 'rockerboy',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['rb_cultural_resonance'],
  },
  {
    id: 'rb_underground_circuit',
    name: 'Underground Circuit',
    flavour: 'The venues they can\'t shut down.',
    stat: '+2 Followers/sec',
    category: 'act2_path',
    act: 2,
    path: 'rockerboy',
    cost: 500000,
    costResource: 'eddies',
    secondaryGenMod: 2,
    prereq: ['rb_first_broadcast'],
  },
  {
    id: 'rb_anti_corp_anthem',
    name: 'Anti-Corp Anthem',
    flavour: 'The song they keep trying to ban.',
    stat: 'Followers multiply during corp events',
    category: 'act2_path',
    act: 2,
    path: 'rockerboy',
    cost: 1000000,
    costResource: 'eddies',
    prereq: ['rb_underground_circuit'],
  },
  {
    id: 'rb_banned_in_three_cities',
    name: 'Banned In Three Cities',
    flavour: 'The best marketing.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'rockerboy',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['rb_anti_corp_anthem'],
  },
  // Act 3 Branch A — Underground Movement
  {
    id: 'rb_followers_currency',
    name: 'Followers as Currency',
    flavour: 'Belief is worth more than eddies.',
    stat: 'Followers convert to all resource types',
    category: 'act3_branch_a',
    act: 3,
    path: 'rockerboy',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
  },
  {
    id: 'rb_direct_action',
    name: 'Direct Action Network',
    flavour: 'The movement that doesn\'t ask permission.',
    stat: 'Followers generate Influence',
    category: 'act3_branch_a',
    act: 3,
    path: 'rockerboy',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['rb_followers_currency'],
    influenceGenMod: 2,
  },
  {
    id: 'rb_the_message',
    name: 'The Message',
    flavour: 'Can\'t be unsaid. Can\'t be unseen.',
    stat: 'Income spikes during social events',
    category: 'act3_branch_a',
    act: 3,
    path: 'rockerboy',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['rb_direct_action'],
  },
  {
    id: 'rb_cultural_infrastructure',
    name: 'Cultural Infrastructure',
    flavour: 'This can\'t be seized. This can\'t be destroyed.',
    stat: 'Permanent Followers floor',
    category: 'act3_branch_a',
    act: 3,
    path: 'rockerboy',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['rb_the_message'],
    incomeMultMod: 2,
  },
  // Act 3 Branch B — Corporate Sellout
  {
    id: 'rb_label_deal',
    name: 'Label Deal',
    flavour: 'You sold the voice. They think they bought the soul.',
    stat: 'Massive eddies, Followers cost',
    category: 'act3_branch_b',
    act: 3,
    path: 'rockerboy',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 1000,
  },
  {
    id: 'rb_sponsored_content',
    name: 'Sponsored Content',
    flavour: 'Brought to you by MiliArms. Probably.',
    stat: 'Steady eddie income',
    category: 'act3_branch_b',
    act: 3,
    path: 'rockerboy',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['rb_label_deal'],
    incomeMod: 2000,
  },
  {
    id: 'rb_brand_partnership',
    name: 'Brand Partnership',
    flavour: 'Your face on their product. Their money in your account.',
    stat: 'Influence from corpo relationships',
    category: 'act3_branch_b',
    act: 3,
    path: 'rockerboy',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['rb_sponsored_content'],
    influenceGenMod: 1,
  },
  {
    id: 'rb_the_compromise',
    name: 'The Compromise',
    flavour: 'The price was everything except the voice.',
    stat: 'Highest eddie ceiling, lowest rep',
    category: 'act3_branch_b',
    act: 3,
    path: 'rockerboy',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['rb_brand_partnership'],
    incomeMultMod: 3,
  },
];

// ─── NOMAD PATH ──────────────────────────────────────────────────────────────

export const NOMAD_UPGRADES: UpgradeDef[] = [
  {
    id: 'nm_pack_recognition',
    name: 'Pack Recognition',
    flavour: 'They know the rig. They know you\'re pack.',
    stat: 'Unlocks Road Cred generation (+0.5/sec)',
    category: 'act2_path',
    act: 2,
    path: 'nomad',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
  },
  {
    id: 'nm_territory_claim',
    name: 'Territory Claim',
    flavour: 'These roads are ours. That\'s not a claim. It\'s a fact.',
    stat: '+7 eddies/sec per Road Cred',
    category: 'act2_path',
    act: 2,
    path: 'nomad',
    cost: 100000,
    costResource: 'eddies',
    prereq: ['nm_pack_recognition'],
  },
  {
    id: 'nm_route_expansion',
    name: 'Route Expansion',
    flavour: 'The roads go further every season.',
    stat: 'Road Cred cap +100',
    category: 'act2_path',
    act: 2,
    path: 'nomad',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['nm_territory_claim'],
  },
  {
    id: 'nm_supply_run',
    name: 'Supply Run',
    flavour: 'There and back. Profitable both ways.',
    stat: '+1 Road Cred/sec',
    category: 'act2_path',
    act: 2,
    path: 'nomad',
    cost: 500000,
    costResource: 'eddies',
    secondaryGenMod: 1,
    prereq: ['nm_pack_recognition'],
  },
  {
    id: 'nm_badlands_knowledge',
    name: 'Badlands Knowledge',
    flavour: 'You know the roads they don\'t put on maps.',
    stat: 'Territory events -40%',
    category: 'act2_path',
    act: 2,
    path: 'nomad',
    cost: 1000000,
    costResource: 'eddies',
    prereq: ['nm_supply_run'],
  },
  {
    id: 'nm_pack_elder_status',
    name: 'Pack Elder Status',
    flavour: 'The kind of respect that takes years to earn.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'nomad',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['nm_badlands_knowledge'],
  },
  // Act 3 Branch A — Badlands Empire
  {
    id: 'nm_territory_control_1',
    name: 'Territory Control I',
    flavour: 'First region. Held by presence alone.',
    stat: 'Region income +',
    category: 'act3_branch_a',
    act: 3,
    path: 'nomad',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 500,
  },
  {
    id: 'nm_road_tax',
    name: 'Road Tax',
    flavour: 'Unofficial. Universally understood.',
    stat: 'Passive income from all traffic',
    category: 'act3_branch_a',
    act: 3,
    path: 'nomad',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['nm_territory_control_1'],
    incomeMod: 1000,
  },
  {
    id: 'nm_pack_alliances',
    name: 'Pack Alliances',
    flavour: 'The roads are stronger together.',
    stat: 'Inter-pack passive bonuses',
    category: 'act3_branch_a',
    act: 3,
    path: 'nomad',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['nm_road_tax'],
    incomeMultMod: 1.5,
  },
  {
    id: 'nm_the_badlands',
    name: 'The Badlands',
    flavour: 'The government never held these roads. They never will.',
    stat: 'Immune to government events',
    category: 'act3_branch_a',
    act: 3,
    path: 'nomad',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['nm_pack_alliances'],
    incomeMultMod: 2,
  },
  // Act 3 Branch B — City Smuggler
  {
    id: 'nm_urban_routes',
    name: 'Urban Routes',
    flavour: 'The city has roads they don\'t map and times they don\'t watch.',
    stat: 'High risk high reward supply runs',
    category: 'act3_branch_b',
    act: 3,
    path: 'nomad',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 700,
  },
  {
    id: 'nm_corpo_blind_eye',
    name: 'Corpo Blind Eye',
    flavour: 'They pay you not to be a problem.',
    stat: 'Some corps pay for discreet movement',
    category: 'act3_branch_b',
    act: 3,
    path: 'nomad',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['nm_urban_routes'],
    incomeMod: 1500,
  },
  {
    id: 'nm_night_market',
    name: 'Night Market Access',
    flavour: 'Opens at midnight. Closes when it closes.',
    stat: 'Income burst events',
    category: 'act3_branch_b',
    act: 3,
    path: 'nomad',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['nm_corpo_blind_eye'],
  },
  {
    id: 'nm_the_run',
    name: 'The Run',
    flavour: 'Single load. Single shot. All or nothing.',
    stat: 'Massive income event, high risk',
    category: 'act3_branch_b',
    act: 3,
    path: 'nomad',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['nm_night_market'],
    incomeMultMod: 2.5,
  },
];

// ─── MEDIA PATH ──────────────────────────────────────────────────────────────

export const MEDIA_UPGRADES: UpgradeDef[] = [
  {
    id: 'media_first_source',
    name: 'First Source',
    flavour: 'Anonymous. Nervous. Worth listening to.',
    stat: 'Unlocks Sources generation (+0.3/sec)',
    category: 'act2_path',
    act: 2,
    path: 'media',
    cost: 30000,
    costResource: 'eddies',
    secondaryGenMod: 0.3,
  },
  {
    id: 'media_story_pipeline',
    name: 'Story Pipeline',
    flavour: 'The story is always there. You just need someone to tell it.',
    stat: '+10 eddies/sec per Source',
    category: 'act2_path',
    act: 2,
    path: 'media',
    cost: 100000,
    costResource: 'eddies',
    prereq: ['media_first_source'],
  },
  {
    id: 'media_dead_drop_net',
    name: 'Dead Drop Network',
    flavour: 'The information comes to you.',
    stat: 'Sources cap +50',
    category: 'act2_path',
    act: 2,
    path: 'media',
    cost: 300000,
    costResource: 'eddies',
    prereq: ['media_story_pipeline'],
  },
  {
    id: 'media_intel_feed',
    name: 'Intel Feed',
    flavour: 'Constant stream. Most of it useless. Some of it gold.',
    stat: '+0.5 Sources/sec',
    category: 'act2_path',
    act: 2,
    path: 'media',
    cost: 500000,
    costResource: 'eddies',
    secondaryGenMod: 0.5,
    prereq: ['media_first_source'],
  },
  {
    id: 'media_source_protection',
    name: 'Source Protection Protocol',
    flavour: 'The story is nothing without the people behind it.',
    stat: 'Source burnout events -40%',
    category: 'act2_path',
    act: 2,
    path: 'media',
    cost: 1000000,
    costResource: 'eddies',
    prereq: ['media_intel_feed'],
  },
  {
    id: 'media_embedded_journalist',
    name: 'Embedded Journalist',
    flavour: 'Access they think they control.',
    stat: 'Gates Act 2 boss',
    category: 'act2_path',
    act: 2,
    path: 'media',
    cost: 3000000,
    costResource: 'eddies',
    prereq: ['media_source_protection'],
  },
  // Act 3 Branch A — Whistleblower Network
  {
    id: 'media_explosive_story',
    name: 'Explosive Story',
    flavour: 'The truth they can\'t suppress.',
    stat: 'Periodic massive Influence spikes',
    category: 'act3_branch_a',
    act: 3,
    path: 'media',
    branch: 'a',
    cost: 5000000,
    costResource: 'eddies',
    influenceGenMod: 3,
  },
  {
    id: 'media_document_vault',
    name: 'Document Vault',
    flavour: 'Everything stored. Everything ready.',
    stat: 'Stored intel generates passive income',
    category: 'act3_branch_a',
    act: 3,
    path: 'media',
    branch: 'a',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['media_explosive_story'],
    incomeMod: 1000,
  },
  {
    id: 'media_anon_network',
    name: 'Anonymous Network',
    flavour: 'No names. No faces. No evidence.',
    stat: 'Sources immune to detection',
    category: 'act3_branch_a',
    act: 3,
    path: 'media',
    branch: 'a',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['media_document_vault'],
  },
  {
    id: 'media_the_truth',
    name: 'The Truth',
    flavour: 'Can\'t be bought. Can\'t be buried.',
    stat: 'Highest Influence ceiling in the game',
    category: 'act3_branch_a',
    act: 3,
    path: 'media',
    branch: 'a',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['media_anon_network'],
    incomeMultMod: 2.5,
  },
  // Act 3 Branch B — Corporate Embedded
  {
    id: 'media_press_credentials',
    name: 'Press Credentials',
    flavour: 'The badge they want to see. The questions they don\'t.',
    stat: 'Corpo access generates steady income',
    category: 'act3_branch_b',
    act: 3,
    path: 'media',
    branch: 'b',
    cost: 5000000,
    costResource: 'eddies',
    incomeMod: 800,
  },
  {
    id: 'media_managed_narrative',
    name: 'Managed Narrative',
    flavour: 'The story they want. The access you need.',
    stat: 'Reduce all hostile events',
    category: 'act3_branch_b',
    act: 3,
    path: 'media',
    branch: 'b',
    cost: 20000000,
    costResource: 'eddies',
    prereq: ['media_press_credentials'],
  },
  {
    id: 'media_exclusivity_deal',
    name: 'Exclusivity Deal',
    flavour: 'Their story. Your price.',
    stat: 'Income immunity periods',
    category: 'act3_branch_b',
    act: 3,
    path: 'media',
    branch: 'b',
    cost: 75000000,
    costResource: 'eddies',
    prereq: ['media_managed_narrative'],
    incomeMod: 2000,
  },
  {
    id: 'media_the_compromise',
    name: 'The Compromise',
    flavour: 'High steady income. Lower Influence ceiling. You know what you chose.',
    stat: 'High steady income, lower Influence cap',
    category: 'act3_branch_b',
    act: 3,
    path: 'media',
    branch: 'b',
    cost: 200000000,
    costResource: 'eddies',
    prereq: ['media_exclusivity_deal'],
    incomeMultMod: 2,
  },
];

// ─── GHOST MEMORY UPGRADES ──────────────────────────────────────────────────

export const GHOST_UNIVERSAL_UPGRADES: UpgradeDef[] = [
  {
    id: 'gm_street_memory',
    name: 'Street Memory',
    flavour: 'You\'ve done this before. The body remembers.',
    stat: 'Act 1 income ×1.2',
    category: 'ghost_universal',
    act: 1,
    cost: 1,
    costResource: 'ghost_tokens',
    incomeMultMod: 1.2,
  },
  {
    id: 'gm_worn_routes',
    name: 'Worn Routes',
    flavour: 'The longer you\'ve been gone, the more you\'ve earned.',
    stat: 'Offline cap +4 hrs',
    category: 'ghost_universal',
    act: 1,
    cost: 1,
    costResource: 'ghost_tokens',
    offlineCapHours: 4,
    maxLevel: 3,
  },
  {
    id: 'gm_seed_capital',
    name: 'Seed Capital',
    flavour: 'You know where to get started.',
    stat: 'Start with bonus eddies',
    category: 'ghost_universal',
    act: 1,
    cost: 2,
    costResource: 'ghost_tokens',
  },
  {
    id: 'gm_ghost_contacts',
    name: 'Ghost Contacts',
    flavour: 'They remember you. That works in your favour.',
    stat: 'ECHO/RAVEN/CIPHER active from run start',
    category: 'ghost_universal',
    act: 1,
    cost: 2,
    costResource: 'ghost_tokens',
  },
  {
    id: 'gm_hardened_signal',
    name: 'Hardened Signal',
    flavour: 'Harder to jam. Harder to trace. Harder to hurt.',
    stat: 'Event penalties -20% globally',
    category: 'ghost_universal',
    act: 1,
    cost: 3,
    costResource: 'ghost_tokens',
  },
  {
    id: 'gm_the_long_game',
    name: 'The Long Game',
    flavour: 'You play for years. Most people play for weeks.',
    stat: 'Rep scales income: +1.5% per Rep level',
    category: 'ghost_universal',
    act: 1,
    cost: 3,
    costResource: 'ghost_tokens',
  },
];

export const GHOST_PATH_UPGRADES: UpgradeDef[] = [
  // SOLO ghost nodes
  { id: 'gp_solo_1', name: 'Combat Reflex', flavour: 'The muscle remembers.', stat: 'Heat generation rate +25%', category: 'ghost_path', act: 2, path: 'solo', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_solo_2', name: 'Soldier\'s Start', flavour: 'Hit the ground running.', stat: 'Begin Act 2 with 50 Heat', category: 'ghost_path', act: 2, path: 'solo', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_solo_1'] },
  { id: 'gp_solo_3', name: 'Veteran\'s Edge', flavour: 'You\'ve faced worse.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'solo', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_solo_2'] },
  { id: 'gp_solo_4', name: 'The Crew', flavour: 'They follow the legend.', stat: 'Act 4 crew slots +1', category: 'ghost_path', act: 4, path: 'solo', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_solo_3'] },
  // NETRUNNER ghost nodes
  { id: 'gp_nr_1', name: 'Ghost Protocol', flavour: 'You know the channels.', stat: 'Bandwidth generation +25%', category: 'ghost_path', act: 2, path: 'netrunner', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_nr_2', name: 'Cold Boot', flavour: 'Up and running before they notice.', stat: 'Begin Act 2 with 100 Bandwidth', category: 'ghost_path', act: 2, path: 'netrunner', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_nr_1'] },
  { id: 'gp_nr_3', name: 'Known Routes', flavour: 'The NET remembers your paths.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'netrunner', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_nr_2'] },
  { id: 'gp_nr_4', name: 'Node Legacy', flavour: 'The network is already waiting.', stat: 'Act 4 ghost nodes cap +2', category: 'ghost_path', act: 4, path: 'netrunner', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_nr_3'] },
  // FIXER ghost nodes
  { id: 'gp_fx_1', name: 'Street Memory', flavour: 'The contacts remember you.', stat: 'Connections generation +25%', category: 'ghost_path', act: 2, path: 'fixer', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_fx_2', name: 'Existing Relationships', flavour: 'They already trust you.', stat: 'Begin Act 2 with 100 Connections', category: 'ghost_path', act: 2, path: 'fixer', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_fx_1'] },
  { id: 'gp_fx_3', name: 'Prior Work', flavour: 'The jobs speak for themselves.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'fixer', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_fx_2'] },
  { id: 'gp_fx_4', name: 'The Rolodex', flavour: 'Some contacts wait for you.', stat: 'Act 4 contract slots +1', category: 'ghost_path', act: 4, path: 'fixer', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_fx_3'] },
  // TECH ghost nodes
  { id: 'gp_tech_1', name: 'Salvage Memory', flavour: 'The hands remember how.', stat: 'Parts generation +25%', category: 'ghost_path', act: 2, path: 'tech', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_tech_2', name: 'Stockpile', flavour: 'You know what to keep.', stat: 'Begin Act 2 with 200 Parts', category: 'ghost_path', act: 2, path: 'tech', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_tech_1'] },
  { id: 'gp_tech_3', name: 'Proven Methods', flavour: 'Not your first time through this.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'tech', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_tech_2'] },
  { id: 'gp_tech_4', name: 'The Blueprint', flavour: 'The design survives.', stat: 'Act 4 production lines cap +1', category: 'ghost_path', act: 4, path: 'tech', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_tech_3'] },
  // MEDTECH ghost nodes
  { id: 'gp_med_1', name: 'Bedside Manner', flavour: 'They trust the hands they\'ve seen before.', stat: 'Patients generation +25%', category: 'ghost_path', act: 2, path: 'medtech', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_med_2', name: 'Existing Cases', flavour: 'Some of them waited.', stat: 'Begin Act 2 with 30 Patients', category: 'ghost_path', act: 2, path: 'medtech', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_med_1'] },
  { id: 'gp_med_3', name: 'Clinical Experience', flavour: 'The diagnosis is faster now.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'medtech', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_med_2'] },
  { id: 'gp_med_4', name: 'The Network Lives', flavour: 'The clinic that never forgets.', stat: 'Act 4 clinic cap +2', category: 'ghost_path', act: 4, path: 'medtech', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_med_3'] },
  // ROCKERBOY ghost nodes
  { id: 'gp_rb_1', name: 'The Old Fans', flavour: 'They never stopped listening.', stat: 'Followers generation +25%', category: 'ghost_path', act: 2, path: 'rockerboy', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_rb_2', name: 'Cult Following', flavour: 'They were waiting for this.', stat: 'Begin Act 2 with 200 Followers', category: 'ghost_path', act: 2, path: 'rockerboy', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_rb_1'] },
  { id: 'gp_rb_3', name: 'The Backcatalogue', flavour: 'The old work still earns.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'rockerboy', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_rb_2'] },
  { id: 'gp_rb_4', name: 'The Movement Waits', flavour: 'It was always going to come back.', stat: 'Act 4 crew conversion rate +20%', category: 'ghost_path', act: 4, path: 'rockerboy', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_rb_3'] },
  // NOMAD ghost nodes
  { id: 'gp_nm_1', name: 'Road Knowledge', flavour: 'You know where the good routes are.', stat: 'Road Cred generation +25%', category: 'ghost_path', act: 2, path: 'nomad', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_nm_2', name: 'Standing Invitation', flavour: 'The pack left the gate open.', stat: 'Begin Act 2 with 75 Road Cred', category: 'ghost_path', act: 2, path: 'nomad', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_nm_1'] },
  { id: 'gp_nm_3', name: 'Pack Memory', flavour: 'They remember the one who came before.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'nomad', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_nm_2'] },
  { id: 'gp_nm_4', name: 'Established Routes', flavour: 'The territory is already marked.', stat: 'Act 4 territory slots +1', category: 'ghost_path', act: 4, path: 'nomad', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_nm_3'] },
  // MEDIA ghost nodes
  { id: 'gp_media_1', name: 'Source Memory', flavour: 'Some of them will talk again.', stat: 'Sources generation +25%', category: 'ghost_path', act: 2, path: 'media', cost: 2, costResource: 'ghost_tokens' },
  { id: 'gp_media_2', name: 'Returning Sources', flavour: 'They heard you were back.', stat: 'Begin Act 2 with 30 Sources', category: 'ghost_path', act: 2, path: 'media', cost: 3, costResource: 'ghost_tokens', prereq: ['gp_media_1'] },
  { id: 'gp_media_3', name: 'Established Drops', flavour: 'The dead drops were never cleared.', stat: 'Act 2 boss cost -20%', category: 'ghost_path', act: 2, path: 'media', cost: 4, costResource: 'ghost_tokens', prereq: ['gp_media_2'] },
  { id: 'gp_media_4', name: 'The Archive', flavour: 'Stories don\'t expire.', stat: 'Act 4 source cap +2', category: 'ghost_path', act: 4, path: 'media', cost: 5, costResource: 'ghost_tokens', prereq: ['gp_media_3'] },
];

// ─── AGGREGATED LOOKUP ───────────────────────────────────────────────────────

export const ALL_UPGRADES: UpgradeDef[] = [
  ...ACT1_UPGRADES,
  ...ACT2_HUSTLE_UPGRADES,
  ...SOLO_UPGRADES,
  ...NETRUNNER_UPGRADES,
  ...FIXER_UPGRADES,
  ...TECH_UPGRADES,
  ...MEDTECH_UPGRADES,
  ...ROCKERBOY_UPGRADES,
  ...NOMAD_UPGRADES,
  ...MEDIA_UPGRADES,
  ...GHOST_UNIVERSAL_UPGRADES,
  ...GHOST_PATH_UPGRADES,
];

export const UPGRADE_MAP: Map<string, UpgradeDef> = new Map(
  ALL_UPGRADES.map(u => [u.id, u])
);

export function getUpgrade(id: string): UpgradeDef | undefined {
  return UPGRADE_MAP.get(id);
}

export function getUpgradesByCategory(category: UpgradeCategory): UpgradeDef[] {
  return ALL_UPGRADES.filter(u => u.category === category);
}

export function getUpgradesByPath(path: CareerPath, category?: UpgradeCategory): UpgradeDef[] {
  return ALL_UPGRADES.filter(u =>
    u.path === path && (category == null || u.category === category)
  );
}
